### ISSUE TITLE
代码似乎不全,有报错

### ISSUE THREAD

**Issue by yangxiaoge** [konglinghai123/zhai#1]
注解掉几个没用的类就行了, 不过侧边栏报IndexOutOfBoundsException下标越界错.

**Comment by konglinghai123** [comment]
不好意思，我昨晚推送的时候，忘记推送那些删除了的文件，现在我删除了。侧边栏我没有写代码，数组越界的错误，如果可以贴一下错误栈就好了。

**Comment by konglinghai123** [comment]
发现了，原来是之前调试的代码没有注释掉

**Comment by yangxiaoge** [comment]
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                          at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                          at java.util.ArrayList.get(ArrayList.java:308)
                                                                          at com.dawnlightning.zhai.model.ImageListModel$2.onSuccess(ImageListModel.java:114)
                                                                          at com.loopj.android.http.TextHttpResponseHandler.onSuccess(TextHttpResponseHandler.java:118)
                                                                          at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
                                                                          at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 

ImageListModel类 114行

**Comment by yangxiaoge** [comment]
楼主很牛逼,继续更新简书哟!

**Comment by konglinghai123** [comment]
感谢你的支持，我准备把这个项目改成用Rxjava+Retrofit，结合Mvp，然后写一篇简书，你觉得怎样

**Comment by yangxiaoge** [comment]
🤓这个可以有，正好想学习mvp模式，retrofit没有深入了解，加油哦，坐等简书更新！

**Comment by yangxiaoge** [comment]
作者最近咋没有更新呢

**Comment by konglinghai123** [comment]
sorry，我最近负责带3个小伙伴一起写代码，而且还要上课，精力不够用啊，不够到时我们成员磨合了，一起维护这个项目，感谢你对我的支持，简书我也好久没更了，因为写思想的东西很抽象，不想贴一下代码那么直接

**Comment by yangxiaoge** [comment]
赞哦，带小伙伴一起学习挺好的，支持你！

**Comment by konglinghai123** [comment]
你可以看我最新的一篇文章，《MVP开发的那些套路》，这是我正在和我的小伙伴一起使用的开发模式

**Comment by yangxiaoge** [comment]
哈哈，今天已经看了，简单易懂，写的挺棒的！我之前都是MVC模式开发维护很麻烦，准备试试MVP，写个Gank（干货）玩玩。
